# Generated by Django 5.0.7 on 2024-07-22 03:50

from django.db import migrations

def populate_authors(apps, schema_editor):
    Author = apps.get_model('books', 'Author')
    User = apps.get_model('auth', 'User')
    
    Author.objects.bulk_create([
        Author(first_name='Isaac', last_name='Asimov'),
        Author(first_name='Philip', last_name='Marques'),
        Author(first_name='George', last_name='Orwell'),
        Author(first_name='J.R.R.', last_name='Tolkien'),
        Author(first_name='William', last_name='Shakespeare'),
    ])

    User.objects.create_superuser('dev', password='asd123123')


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_authors),
    ]
